#!/usr/bin/env python 
# -*- coding: utf-8 -*- 
#
# @author kangao
# @since 2019/11/24

__RINEX_VERSION_TYPE__ = 'RINEX VERSION / TYPE'
__PGM_RUN_BY_DATE__ = 'PGM / RUN BY / DATE'
__COMMENT__ = 'COMMENT'
__MARKER_NAME__ = 'MARKER NAME'
__MARKER_NUMBER__ = 'MARKER NUMBER'
__MARKER_TYPE__ = 'MARKER TYPE'
__OBSERVER_AGENCY__ = 'OBSERVER / AGENCY'
__REC_TYPE_VERS__ = 'REC # / TYPE / VERS'
__ANT_TYPE__ = 'ANT # / TYPE'
__APPROX_POSITION_XYZ__ = 'APPROX POSITION XYZ'
__ANT_DELTA_H_E_N__ = 'ANTENNA: DELTA H/E/N'
__ANT_DELTA_X_Y_Z__ = 'ANTENNA: DELTA X/Y/Z'
__ANT_PHASE_CENTER__ = 'ANTENNA:PHASE CENTER'
__ANT_B_SIGHT_X_Y_Z__ = 'ANTENNA: B.SIGHT XYZ'
__ANT_ZERODIR_AZI__ = 'ANTENNA: ZERODIR AZI'
__ANT_ZERODIR_XYZ__ = 'ANTENNA: ZERODIR XYZ'
__CENTER_OF_MASS_XYZ__ = 'CENTER OF MASS: XYZ'
__SYS_OBS_TYPES__ = 'SYS / # / OBS TYPES'
__SIGNAL_STRENGTH_UNIT__ = 'SIGNAL STRENGTH UNIT'
__INTERVAL__ = 'INTERVAL'
__TIME_OF_FIRST_OBS__ = 'TIME OF FIRST OBS'
__TIME_OF_LAST_OBS__ = 'TIME OF LAST OBS'
__RCV_CLOCK_OFFS_APPL__ = 'RCV CLOCK OFFS APPL'
__SYS_DCBS_APPLIED__ = 'SYS / DCBS APPLIED'
__SYS_PCVS_APPLIED__ = 'SYS / PCVS APPLIED'
__SYS_SCALE_FACTOR__ = 'SYS / SCALE FACTOR'
__SYS_PHASE_SHIFT__ = 'SYS / PHASE SHIFT'
__GLONASS_SLOT_FRQ__ = 'GLONASS SLOT / FRQ #'
__GLONASS_COD_PHS_BIS__ = 'GLONASS COD/PHS/BIS'
__LEAP_SECONDS__ = 'LEAP SECONDS'
__OF_SATELLITES__ = '# OF SATELLITES'
__PRN_OF_OBS__ = 'PRN / # OF OBS'
__END_OF_HEADER__ = 'END OF HEADER'
__IONOSPHERIC_CORR__ = 'IONOSPHERIC CORR'
__TIME_SYSTEM_CORR__ = 'TIME SYSTEM CORR'






